"""English copy for the browser edition. The Japanese source stays authoritative."""

BODY = {
    '1行に複数のカットがあるときは、カットが切り替わる瞬間に <span class="kbd">Tab</span> を押すと、その行のカットの開始時刻も合わせられます。': 'If a line has several cuts, press <span class="kbd">Tab</span> the moment the cut should change to time the cuts of that line too.',
    '<label>速さ <select id="tapRate" aria-label="タップ中の再生速度">': '<label>Speed <select id="tapRate" aria-label="Playback speed while tapping">',
    '<input type="checkbox" id="tapCount"> カウントダウン</label>': '<input type="checkbox" id="tapCount"> Count-in</label>',
    'title="LRC ファイル（タイムスタンプ付きの歌詞）を読み込み、今の歌詞と置き換えます（「元に戻す」で戻せます）">LRC を読み込む': 'title="Load an LRC file (lyrics with time stamps) in place of the current lyrics (Undo brings them back)">Load LRC',
    'aria-label="おまかせのテーマ" title="おまかせのテーマ（選ぶと、その方向の中でおまかせします。必要な部品のスイッチもオンになります）"': 'aria-label="Randomize theme" title="Randomize theme (when set, Randomize stays within that direction and turns on the part sets it needs)"',
    '<label class="theme-row">テーマ<select class="themeSel" aria-label="おまかせのテーマ">': '<label class="theme-row">Theme<select class="themeSel" aria-label="Randomize theme">',
    '<option value="">テーマなし</option><option value="lyricpv">文字PV</option><option value="kinetic">キネティック</option><option value="wa">和風</option><option value="horror">ホラー</option><option value="pop">ポップ</option><option value="ballad">バラード</option>': '<option value="">No theme</option><option value="lyricpv">Lyric video</option><option value="kinetic">Kinetic</option><option value="wa">Japanese</option><option value="horror">Horror</option><option value="pop">Pop</option><option value="ballad">Ballad</option>',
    '<small class="muted">選ぶと、その方向の中でおまかせします</small>': '<small class="muted">Randomize stays within the chosen direction</small>',
    'title="各行の開始時刻を付けた歌詞（.lrc）を書き出します。書き出す範囲を選んでいるときは、その行だけを動画の頭からの時刻で書き出します">LRC を書き出す</button>': 'title="Save the lyrics with each line’s start time (.lrc). With an export range, only those lines, timed from the start of the video">Save LRC</button>',
    'title="各行の開始時刻を付けた歌詞（.lrc）を書き出します。書き出す範囲を選んでいるときは、その行だけを動画の頭からの時刻で書き出します">歌詞（LRC）</button>': 'title="Save the lyrics with each line’s start time (.lrc). With an export range, only those lines, timed from the start of the video">Lyrics (LRC)</button>',
    'title="レイアウトや装飾が添える「No.01」「#03」のような数字を描きません（歌詞に含まれる数字はそのまま）"><input id="fxHideNo" type="checkbox"> 飾りの数字を消す': 'title="Leave out the numbers layouts and decorations add, like “No.01” or “#03” (numbers in the lyrics stay)"><input id="fxHideNo" type="checkbox"> Hide decorative numbers',
    'title="レイアウトや装飾が添える「00:12.34」のような時刻を描きません（歌詞に含まれる時刻はそのまま）"><input id="fxHideTime" type="checkbox"> 飾りの時刻を消す': 'title="Leave out the times layouts and decorations add, like “00:12.34” (times in the lyrics stay)"><input id="fxHideTime" type="checkbox"> Hide decorative times',
    '文字PV系の部品を使う': 'Use typographic parts',
    'キネティックの部品を使う': 'Use kinetic parts',
    'ホラーの演出も使う': 'Include horror effects',
    '<small>線・数字・字組みだけで見せる、文字PVらしい部品（約50）</small>': '<small>About 50 parts that work with lines, numbers and type alone, in the spirit of lyric videos</small>',
    '<small>語ごとに動く・跳ねる・積み上がる、動き重視の部品（約50）</small>': '<small>About 50 motion-first parts: words move, bounce and stack one by one</small>',
    '<small>不気味な雰囲気の部品（約50）と配色セット3。オンにすると、おまかせの雰囲気に「ホラー」が加わります</small>': '<small>About 50 eerie parts and 3 styles. When on, Randomize adds a Horror mood</small>',
    '<small>「文」印の手法。オフにすると、おまかせやシャッフルでは選ばれません</small>': '<small>Techniques marked T. When off, Randomize and Shuffle skip them</small>',
    '<small>「キ」印の手法。オフにすると、おまかせやシャッフルでは選ばれません</small>': '<small>Techniques marked K. When off, Randomize and Shuffle skip them</small>',
    '<small>「ホ」印の手法とスタイル。おまかせでは雰囲気が「ホラー」のときだけ使います</small>': '<small>Techniques and styles marked H. Randomize uses them only in the Horror mood</small>',
    'title="スタイル・雰囲気・演出・配色をまるごとランダムに">おまかせ</button>': 'title="Randomize style, mood, effects and palette">Randomize</button>',
    'aria-controls="appMenu">メニュー</button>': 'aria-controls="appMenu">Menu</button>',
    'title="スマホ向けの画面（おまかせを上に固定、行はたたんで表示）">スマホ</button>': 'title="Phone layout (Randomize pinned at the top, lines folded)">Phone</button>',
    '<button class="exp-share primary" hidden>共有して保存</button>': '<button class="exp-share primary" hidden>Share / save</button>',
    '<label class="row center-dir" hidden>縦長のとき<select class="centerDirSel" aria-label="縦長の画面での分け方"><option value="tb">上下に分ける</option><option value="lr">左右に分ける</option></select></label>': '<label class="row center-dir" hidden>On tall frames<select class="centerDirSel" aria-label="Split on tall frames"><option value="tb">Top / bottom</option><option value="lr">Left / right</option></select></label>',
    '<span>統一感</span>': '<span>Unified look</span>',
    '<span>文字整列</span>': '<span>Typesetting</span>',
    'title="保存先のファイルを先に選び、そこへ直接書き込みます。長い曲・1080p 以上でブラウザのメモリが足りずに失敗するときに使ってください（Chrome / Edge）">大きな動画用（ファイルに直接保存）</button>': 'title="Pick the file first; the video is written straight into it. Use this when long songs or 1080p and above fail because the browser runs out of memory (Chrome / Edge)">For large videos (save straight to a file)</button>',
    'title="保存先のファイルを先に選び、そこへ直接書き込みます。長い曲・1080p 以上でブラウザのメモリが足りずに失敗するときに使ってください（Chrome / Edge）">MP4（大きな動画用・ファイルに直接保存）</button>': 'title="Pick the file first; the video is written straight into it. Use this when long songs or 1080p and above fail because the browser runs out of memory (Chrome / Edge)">MP4 (large videos, save straight to a file)</button>',
    '<span>中央を空ける（キャラクター用）<small>中央にキャラクターなどを重ねる前提で、文字と演出を横長の画面では左右、縦長の画面では上下に、行ごとに交互に置きます。背景と画面効果は全体のままです（プレビューには空ける範囲を点線で表示）</small></span>': '<span>Keep the centre free (for a character)<small>For a character or other footage in the middle: lyrics and their effects go to the left / right on wide frames and top / bottom on tall ones, alternating line by line. Backgrounds and screen effects still cover the whole frame (the preview outlines the free area with a dotted line)</small></span>',
    'title="歌詞と、行ごとのタイミング・指定・書き出す範囲を消します（「元に戻す」か Ctrl+Z で戻せます）">歌詞を消す</button>': 'title="Clear the lyrics with their line timings, per-line settings and export range (Undo or Ctrl+Z brings them back)">Clear lyrics</button>',
    'title="歌詞・曲・設定・履歴をすべて消して、最初の状態に戻します">初期化</button>': 'title="Clear lyrics, song, settings and history and start over">Reset</button>',
    '<h2 id="resetTitle">初期化</h2>': '<h2 id="resetTitle">Reset</h2>',
    '<p>次のものをすべて消して、最初の状態に戻します。<strong>元に戻すことはできません。</strong></p>': '<p>This clears everything below and starts over. <strong>It cannot be undone.</strong></p>',
    '<li>歌詞・曲名・アーティスト</li>': '<li>Lyrics, song title and artist</li>',
    '<li>読み込んだ曲（このブラウザに残していた分も）</li>': '<li>The loaded song (including the copy kept in this browser)</li>',
    '<li>タイミング・行ごとの指定・書き出す範囲</li>': '<li>Timing, per-line settings and export range</li>',
    '<li>スタイル・演出・配色・書体などの設定</li>': '<li>Style, motion, palette, fonts and other settings</li>',
    '<li>案の履歴（◀ ▶）と、歌詞・タイミングの「元に戻す」の履歴</li>': '<li>Variation history (◀ ▶) and the lyrics / timing undo history</li>',
    '<p class="terms-sub">表示モード（かんたん／詳細）・プレビューの音量・画面の言語はそのままです。保存したプロジェクトファイル（.json）も消えません。</p>': '<p class="terms-sub">Simple / Advanced mode, preview volume and the interface language stay as they are. Saved project files (.json) are not affected.</p>',
    '<button value="cancel" class="ghost">やめる</button><button value="reset" class="danger">初期化する</button>': '<button value="cancel" class="ghost">Cancel</button><button value="reset" class="danger">Reset</button>',
    '<li><code>[間奏 8]</code> … 8秒の間奏（歌詞は出さず、背景と装飾だけ）。秒数を省くと4秒、タップ同期やマーカーで長さを合わせられます</li>': '<li><code>[interlude 8]</code> … an 8-second instrumental part (no lyrics, background and decorations only). Without a number it lasts 4 seconds; tap sync or markers set its length</li>',
    '<button class="tour-skip ghost small">スキップ</button>': '<button class="tour-skip ghost small">Skip</button>',
    '<button class="tour-prev ghost small">戻る</button>': '<button class="tour-prev ghost small">Back</button>',
    '<button class="tour-next primary small">次へ</button>': '<button class="tour-next primary small">Next</button>',
    'title="かんたんモードの使い方を案内します" aria-label="使い方の案内"': 'title="A short tour of the Simple mode" aria-label="Tour"',
    '押し間違えたら <span class="kbd">Backspace</span> か「1つ戻る」。途中の行からやり直すときは、行一覧の ◎ を押します。': ' A wrong tap? Press <span class="kbd">Backspace</span> or “Undo tap”. To redo from a line in the middle, press ◎ in the line list.',
    '<button id="tapBack" class="ghost">1つ戻る</button>': '<button id="tapBack" class="ghost">Undo tap</button>',
    '行の区切り（上の目盛り）はドラッグで動かせます。<span class="kbd">Shift</span> で拍に吸着しない': 'Drag the line markers (top) to move line starts. Hold <span class="kbd">Shift</span> to ignore beats',
    'title="歌詞・タイミングの変更を元に戻す（Ctrl+Z）" disabled>元に戻す</button>': 'title="Undo lyric and timing changes (Ctrl+Z)" disabled>Undo</button>',
    'title="縮小" aria-label="タイムラインを縮小"': 'title="Zoom out" aria-label="Zoom the timeline out"',
    'title="拡大（タイムライン上でホイールでも）" aria-label="タイムラインを拡大"': 'title="Zoom in (or scroll on the timeline)" aria-label="Zoom the timeline in"',
    'title="全体を表示">全体</button>': 'title="Show the whole song">Fit</button>',
    'aria-label="タイムライン（クリックで移動・行の区切りはドラッグで調整）"': 'aria-label="Timeline (click to seek, drag line markers to adjust)"',
    '<span class="rng-lab">書き出す範囲</span>': '<span class="rng-lab">Export range</span>',
    'aria-label="書き出す範囲の最初の行"': 'aria-label="First line to export"',
    'aria-label="書き出す範囲の最後の行"': 'aria-label="Last line to export"',
    '<option value="en">English</option>': '<option value="en">English</option>',
    '後景（背景のグラフィックと歌詞の後ろの装飾）と前景（歌詞とその装飾・ゴースト）を、別々のフォルダ（back / front）に透過PNGで書き出します。画面全体の演出は両方にかかるので、前景を後景の上に重ねると通常の見た目になります': 'Transparent PNGs in two folders: back/ (background graphic and the decorations behind the lyrics) and front/ (lyrics, their decorations and ghosts). Screen effects are applied to both, so front over back matches the normal look.',
    '透過PNG 前景／後景（ZIP）': 'Transparent PNG layers (ZIP)',
    'title="クリックで消音／解除（プレビューだけ。書き出しの音量は変わりません）">音量</button>': 'title="Click to mute / unmute (preview only — exports keep the original level)">Vol</button>',
    'aria-label="プレビューの音量"': 'aria-label="Preview volume"',
    '歌詞の言語': 'Lyrics language', '<option value="auto">自動判定</option>': '<option value="auto">Auto-detect</option>',
    '<button id="btnAddFont">追加</button>': '<button id="btnAddFont">Add</button>',
    '曲名': 'Song title', '自動': 'Auto',
    '曲名（タイトルカード・HUDに表示）': 'Song title (shown on title cards and HUD)',
    'アーティスト': 'Artist', '表示モード': 'Editor mode',
    'おまかせボタン中心のシンプルな画面': 'A simple workspace focused on automatic creation',
    'すべての設定を表示': 'Show all settings',
    '保存したプロジェクト(.json)を開く': 'Open a saved project (.json)',
    'プロジェクトを .json で保存': 'Save project as .json',
    'After Effects パネル用の構成データを書き出す': 'Export project data for the After Effects panel',
    '出力物の権利とライセンス': 'Rights and licenses for your exports',
    '歌詞とタイミング': 'Lyrics and timing', 'スタイルと書き出し': 'Style and export',
    '歌詞（1行 = 1フレーズ）': 'Lyrics (one phrase per line)',
    '1行が1フレーズ。空行は少し間を空けます': 'One phrase per line. A blank line adds a short pause.',
    '夜明けの色を/覚えてる': 'I remember/the dawn',
    'でカットの切れ目を指定': 'marks a cut boundary',
    '… 強調（大きく・インパクト寄りの演出）': '… emphasis (larger, stronger effects)',
    '… フラッシュと揺れを入れる': '… adds a flash and shake',
    '… 注釈レイアウトの小さな文字': '… smaller text in annotation layouts',
    '… LRC のタイムスタンプをそのまま使用': '… uses an LRC timestamp',
    'で始まる行 … コメント（無視）': 'starts a comment (ignored)',
    '行末の': 'A trailing', '透明': 'transparent', '歌詞|ruby or note': 'lyrics|reading or note',
    '歌詞': 'Lyrics', '曲とタイミング': 'Audio and timing',
    '曲なし（読み込むと拍を検出してカットを合わせます）': 'No audio. Import a song to detect beats and align cuts.',
    'mp3 / wav / m4a など': 'MP3, WAV, M4A and more',
    '曲を読み込む': 'Import audio', '曲を再生しながら各行の頭でタップ': 'Tap at the start of each line while the song plays',
    'タップで同期': 'Tap to sync', '開始(秒)': 'Start (s)', '行の長さ': 'Line duration',
    '拍にスナップ': 'Snap to beat', '手動タイミングを消す': 'Clear manual timing',
    '曲に合わせて、各行が始まる瞬間に': 'Press', 'かボタンを押してください。': 'or the button as each line starts.',
    '次:': 'Next:', '終了する': 'Finish', '行とカット': 'Lines and cuts',
 'このカットだけ差し替え': 'Replace on this cut only',
 'このカットだけ構成を再抽選': 'Reshuffle this cut only',
 'このカットだけ手法をランダムに': 'Randomize this cut only',
 'このカットをシャッフル': 'Shuffled this cut',
 'このカットをおまかせ': 'Randomized this cut',
    '再生位置': 'Playback position', 'タイムライン（クリックで移動）': 'Timeline (click to seek)',
    '前の案に戻る': 'Previous variation', '次の案へ進む': 'Next variation',
    '設定はそのままで構成だけ再抽選（ロックした行は維持）': 'Shuffle the arrangement, keeping locked lines',
    'スタイル・雰囲気・演出・配色をまるごとランダムに（キー R）': 'Randomize style, mood, effects and colors (R)',
    '押すたびに、スタイル・雰囲気・動き・配色・構成がまるごと変わります。キーボードの': 'Each click changes the style, mood, motion, colors and arrangement. Press',
    'でも実行できます。': 'to do the same.',
    '最初の公開版のあとに追加した約350の演出・配色セット12・書体6も、おまかせやシャッフルの候補にします（オフのときは最初の公開版の演出だけ）': 'Include about 350 more effects, 12 styles and 6 fonts in random picks. Off uses the original set.',
    '提灯・はがき・障子・扇・家紋・青海波・桜の花びらなどの和風グラフィック。オフにすると、おまかせやシャッフルで選ばれません': 'Include Japanese motifs such as lanterns, postcards, shoji, fans, family crests, waves and cherry blossoms in random picks.',
    '「追加」印の手法・スタイル・書体。オフのときは、おまかせやシャッフルで最初の公開版の演出だけを使います': 'Include techniques, styles and fonts marked New in automatic picks.',
    '「和」印の手法とスタイル。オフにすると、おまかせやシャッフルでは選ばれません（追加分の判定のあとに適用。行ごとに手動で指定した場合は使えます）': 'Include techniques and styles marked JP in automatic picks. Manual selections remain available.',
    '追加分の演出も使う': 'Include new effects', '和風の演出も使う': 'Include Japanese motifs',
    'スタイルだけ別のものに': 'Change the style only', 'アクセント・ズレ色A/Bをランダムに': 'Randomize accent and offset colors',
    '動き・グリッチ・使う手法の雰囲気だけ': 'Change motion, glitch and technique mood',
    'レイアウトと動きの組み合わせだけ': 'Change the arrangement and motion only',
    '画面比': 'Aspect ratio', '解像度': 'Resolution', '画質': 'Quality',
    '通常（スタイルの背景）': 'Style background', 'グリーンバック（合成用）': 'Green screen (compositing)',
    'ブラックバック（合成用）': 'Black background (compositing)',
    'MP4 を書き出す': 'Export MP4', '書き出した動画の権利について': 'Rights to exported videos',
    'フォントの役割': 'Font roles', 'PCのフォント名（例: 游明朝）': 'Installed font name (e.g. Arial)',
    'フォントファイル（.ttf/.otf）': 'Font file (.ttf/.otf)',
    'アクセント・ズレ色': 'Accent and offset colors',
    '全シーンに適用。背景に合わせて明るさを自動調整します': 'Applies to every scene. Brightness adapts to the background.',
    '自分の色で上書き': 'Use custom colors', 'ランダムに配色': 'Randomize palette',
    '背景・文字色': 'Background and text colors', 'メインの背景と文字を自分の色にする': 'Use custom background and text colors',
    '動きを何枚/秒で描くか（出力fpsとは別）': 'Motion drawings per second (independent of export fps)',
    'フル（出力fpsのまま）': 'Full (export fps)', '2コマ打ち（12枚/秒）': 'On twos (12 drawings/s)',
    '3コマ打ち（8枚/秒）': 'On threes (8 drawings/s)',
    'スタイル次第': 'Auto (by style)', '常に表示': 'Always show', '表示しない': 'Hide',
    '同じシードなら同じ構成になります。行ごとの「再抽選」「ロック」は左の行リストから。': 'The same seed produces the same arrangement. Reroll or lock individual lines in the list on the left.',
    '手法を名前で絞り込み': 'Filter techniques by name',
    '画面に見えているプレビューは自動でループします。': 'Previews on screen loop automatically.',
    'グリーンバック／ブラックバックにすると、白い文字と演出だけを単色の背景の上に描きます（背景の模様・紙の質感・粒子・周辺減光は入りません）。プレビューにもそのまま反映されます。グリーンバックは動画編集ソフトのクロマキーで、ブラックバックは「スクリーン」合成や輝度キーで抜いて、別の映像の上に重ねられます。': 'Green screen and black background render white text and effects over a solid color, without background patterns, paper texture, particles or vignette. The preview shows the export. Use a chroma key for green or Screen blending / a luma key for black to composite over footage.',
    '曲を動画に含める': 'Include audio in video', '連番PNG（ZIP）': 'PNG sequence (ZIP)',
    '透過PNG（ZIP・背景なし）': 'Transparent PNG (ZIP)',
    '書き出した動画・画像の権利とライセンスについて': 'Rights and licenses for exported videos and images',
    '書き出しはこのブラウザの中で行われます（Chrome / Edge 推奨）。': 'Export runs in your browser (Chrome or Edge recommended).',
    'このツールで作った': 'You own the', '動画や画像（出力物）の権利は、作った人': 'videos and images you create',
    'に帰属します。': '.', '※ 使った歌詞や曲の権利は、それぞれの権利者に帰属します。': 'Lyrics and music remain the property of their respective rights holders.',
    'ツール本体は': 'The tool is released under the', 'ライセンス': 'license',
    'で公開しています。詳細なライセンスはこちら：': '. See the license at:',
    '入力した歌詞や曲は、このブラウザの中だけで処理され、サーバーには送信されません。': 'Your lyrics and audio are processed in this browser and are not sent to a server.',
    '使用しているオープンソース': 'Open source software', 'MP4 書き出し：': 'MP4 export: ',
    'フォント：': 'Fonts: ', '配布の各書体': 'typefaces', '閉じる': 'Close',
    'かんたん': 'Simple', '詳細': 'Advanced', '開く': 'Open', '保存': 'Save',
    'AE用に書き出し': 'Export for AE', '利用について': 'About / rights',
    '記法': 'Syntax', 'プレビュー': 'Preview', '再生': 'Play', 'ループ': 'Loop',
    '前の案': 'Previous', '次の案': 'Next', 'シャッフル': 'Shuffle', 'おまかせで作る': 'Create a variation',
    'おまかせ': 'Randomize', 'いまの案': 'Current variation', 'ここだけ変える': 'Change one thing',
    'スタイル': 'Style', '配色': 'Palette', '雰囲気': 'Mood', '構成': 'Arrangement',
    '書き出し': 'Export', '縦': 'portrait', '背景': 'Background',
    '追加': 'New', '和': 'JP', '演出': 'Effects', '手法': 'Techniques',
    'コマ打ち': 'Frame stepping', 'フラッシュ': 'Flash', 'シード': 'Seed', '新しいシード': 'New seed',
    '標準': 'Standard', '最高': 'Maximum', '高': 'High', '中止': 'Cancel',
    '行ループ': 'Line loop', 'カットループ': 'Cut loop',
    '全体を繰り返し': 'Loop the whole piece', 'この行を繰り返し': 'Loop this line',
    'このカットを繰り返し': 'Loop this cut', '繰り返しなし': 'No loop',







    'このカットだけ差し替え': 'Replace only this cut',
    'このカットだけ構成を再抽選': 'Re-roll the composition of only this cut',
    'このカットだけ手法をランダムに': 'Randomize the technique of only this cut',
    'このカットをシャッフル': 'Shuffle this cut',
    'このカットをおまかせ': 'Randomise this cut',
    'このカットをおまかせ': 'Randomize this cut',


}

UI = {
    '`前後の行と順番が入れ替わらないよう ${w.toFixed(2)} 秒にしました`': '`Set to ${w.toFixed(2)} s so the lines stay in order`',
    "'このカットの開始時刻（手動）。空にすると自動に戻ります'": "'Start of this cut (set by hand). Clear it to go back to automatic'",
    "'このカットの開始時刻（自動）。数値を入れると固定します'": "'Start of this cut (automatic). Type a time to fix it'",
    '`${i + 1}行目 カット${k + 1}の開始時刻`': '`Line ${i + 1}, start of cut ${k + 1}`',
    '`LRC を読み込みました（時刻付き ${n} 行・「元に戻す」で戻せます）`': '`LRC loaded (${n} timed lines · Undo brings the old lyrics back)`',
    "'この行にはこれ以上カットがありません'": "'This line has no more cuts'",
    "'LRC ファイルが大きすぎます'": "'The LRC file is too large'",
    "'LRC を読み込めませんでした'": "'Could not read the LRC file'",
    "'今の歌詞を LRC の内容に置き換えます（行ごとの時刻・指定・書き出す範囲も消えます。「元に戻す」で戻せます）。よろしいですか？'": "'Replace the current lyrics with the LRC file? (Line times, per-line settings and the export range are cleared too. Undo brings them back.)'",
    '`おまかせ（${themeName(th)}）：`': '`Randomized (${themeName(th)}): `',
    "'文字PV系の部品：使う'": "'Typographic parts: on'",
    "'文字PV系の部品：使わない（おまかせ・シャッフルで選ばれません）'": "'Typographic parts: off (not picked by Randomize or Shuffle)'",
    "'キネティックの部品：使う'": "'Kinetic parts: on'",
    "'キネティックの部品：使わない（おまかせ・シャッフルで選ばれません）'": "'Kinetic parts: off (not picked by Randomize or Shuffle)'",
    "'ホラーの演出：使う（おまかせの雰囲気に「ホラー」が加わります）'": "'Horror effects: on (Randomize adds a Horror mood)'",
    "'ホラーの演出：使わない'": "'Horror effects: off'",
    "'（このセットがオフのため、おまかせでは選ばれません）'": "' (this set is off for automatic picks)'",
    "'（このセットがオフのため、自動では選ばれません）'": "' (this set is off for automatic picks)'",
    "{ name: 'ホラー', badge: 'ホ' }": "{ name: 'Horror', badge: 'H' }",
    "{ name: '文字PV系', badge: '文' }": "{ name: 'Typographic', badge: 'T' }",
    "{ name: 'キネティック', badge: 'キ' }": "{ name: 'Kinetic', badge: 'K' }",
    "'スマホの画面では 1080p で書き出します'": "'In the Phone layout the export is 1080p at most'",
    "`読み込んだ書体（${[...new Set(lost)].join('・')}）がこのブラウザにないため、書き出しを止めました。「フォント」から同じファイルを読み込み直すか、別の書体を選んでください`": "`The uploaded font (${[...new Set(lost)].join(', ')}) is not in this browser, so the export was stopped. Load the same file again under Fonts, or pick another font`",
    "`読み込んだ書体（${missing.join('・')}）がこのブラウザにありません。「フォント」から同じファイルを読み込み直してください（それまでは近い書体で表示します）`": "`The uploaded font (${missing.join(', ')}) is not in this browser. Load the same file again under Fonts (a similar font is used until then)`",
    "'縦長の画面：左右に分けます'": "'Tall frames: split left / right'",
    "'縦長の画面：上下に分けます'": "'Tall frames: split top / bottom'",
    "'（最初の方法では失敗したため、別のエンコーダーで書き出しました）'": "' (the first method failed, so another encoder was used)'",
    "'統一感：オン（パートごとにそろえ、キメ・モーフ・太さも使います）'": "'Unified look: on (parts match; hits, morphs and weight too)'",
    "'保存先を開けませんでした: '": "'Could not open the file: '",
    '`・「${fileName}」に保存しました`': '` · saved to “${fileName}”`',
    "'統一感：オフ'": "'Unified look: off'",
    "'文字整列：オン（字間・助詞・英字・0.2秒先・効果控えめ）'": "'Typesetting: on (spacing, particles, Latin, 0.2 s lead, fewer effects)'",
    "'文字整列：オフ'": "'Typesetting: off'",
    "`中央を空けました：文字と演出を${tall ? '上下' : '左右'}に置きます`": "`Centre kept free: lyrics and effects go ${tall ? 'top / bottom' : 'left / right'}`",
    "'中央を空けるのをやめました'": "'Centre no longer kept free'",
    "'歌詞を消しました（「元に戻す」か Ctrl+Z で戻せます）'": "'Lyrics cleared (Undo or Ctrl+Z brings them back)'",
    "'初期化しました'": "'Reset done'",
    "'歌詞・曲・設定・履歴をすべて消して、最初の状態に戻します。元に戻すことはできません。'": "'Clear lyrics, song, settings and history and start over? This cannot be undone.'",
    "(ln.interlude ? ' 間奏' : '')": "(ln.interlude ? ' inst.' : '')",
    "`〔間奏${ln.secs ? ' ' + ln.secs + '秒' : ''}〕`": "`[interlude${ln.secs ? ' ' + ln.secs + 's' : ''}]`",
    '\'<option value="">カット 自動</option>\'': '\'<option value="">Cuts: auto</option>\'',
    '`<option value="${n}">カット ${n}</option>`': '`<option value="${n}">Cuts: ${n}</option>`',
    'title="この行の歌詞を直す" aria-label="${i + 1}行目の歌詞を直す"': 'title="Edit this line’s lyrics" aria-label="Edit the lyrics of line ${i + 1}"',
    'aria-label="${i + 1}行目のカット数"': 'aria-label="Number of cuts in line ${i + 1}"',
    'title="この行からタップで同期し直す" aria-label="${i + 1}行目からタップ"': 'title="Tap sync again from this line" aria-label="Tap sync from line ${i + 1}"',
    'title="書き出す範囲にする（Shift+クリックで範囲を広げる）"': 'title="Set as the export range (Shift+click extends it)"',
    'aria-label="${i + 1}行目を書き出す範囲に"': 'aria-label="Export line ${i + 1}"',
    '`${ln.index + 1}行目の歌詞`': '`Lyrics of line ${ln.index + 1}`',
    "'記法（/ 区切り・*強調*・行末の ! ・| 注釈・[間奏 8]）もそのまま使えます。Enter で確定、Esc で取り消し'": "'Lyric syntax works here too (/ cut, *emphasis*, final !, | note, [interlude 8]). Enter to apply, Esc to cancel'",
    '`${ln.index + 1}行目の歌詞を直しました`': '`Line ${ln.index + 1} updated`',
    "'元に戻しました' : 'やり直しました'": "'Undone' : 'Redone'",
    "`書き出す範囲：${R2.from + 1}${R2.to > R2.from ? '〜' + (R2.to + 1) : ''}行目` : '書き出す範囲：全体'": "`Export range: line ${R2.from + 1}${R2.to > R2.from ? '–' + (R2.to + 1) : ''}` : 'Export range: whole song'",
    "'〔間奏〕' : ln.text).slice(0, 14)": "'[interlude]' : ln.text).slice(0, 14)",
    "opts(el, '全体')": "opts(el, 'Whole song')",
    '`${J.fmtTime(r.t0)} 〜 ${J.fmtTime(r.t1)}（${(r.t1 - r.t0).toFixed(1)}秒）` : `全体（${S.plan.duration.toFixed(1)}秒）`': '`${J.fmtTime(r.t0)} – ${J.fmtTime(r.t1)} (${(r.t1 - r.t0).toFixed(1)}s)` : `Whole song (${S.plan.duration.toFixed(1)}s)`',
    "'。このブラウザでは音声が Opus になり、iPhone・QuickTime などでは音が出ないことがあるため、音声を WAV でも保存しました' : '。このブラウザは音声を書き出せないため、音声を WAV で別に保存しました（動画編集ソフトで重ねてください）'": "'. This browser encodes audio as Opus, which iPhone, QuickTime and some players cannot play, so the audio was also saved as WAV' : '. This browser cannot encode audio, so the audio was saved separately as WAV (combine it in a video editor)'",
    "'。曲が読み込まれていないため音声なしです（「曲を読み込む」から読み込み直してください）'": "'. No song is loaded, so the video has no audio (load the song again with “Load song”)'",
    '`${from + 1}行目からタップで同期します（${J.fmtTime(t0)} から再生）`': '`Tap sync from line ${from + 1} (playing from ${J.fmtTime(t0)})`',
    "ln.interlude ? '〔間奏〕' : ln.text} ` : '—'": "ln.interlude ? '[interlude]' : ln.text} ` : '—'",
    "`${S.tap.i + 1}. ${ln.interlude ? '〔間奏〕' : ln.text}`": "`${S.tap.i + 1}. ${ln.interlude ? '[interlude]' : ln.text}`",
    "' · 前回の曲'": "' · last song'",
    "'・前回の曲'": "' · last song'",
    "title: '1. 歌詞を入れる', text: '1行が1フレーズになります。空行で少し間が空き、[間奏 8] と書くと8秒の間奏（背景と装飾だけ）になります。'": "title: '1. Enter lyrics', text: 'One line is one phrase. A blank line adds a short pause; [interlude 8] makes an 8-second instrumental part (background and decorations only).'",
    "title: '2. 曲を読み込む', text: 'mp3 などを読み込むと拍を検出して、カットの切り替わりを合わせます。曲がなくても作れます。「タップで同期」で行の頭を合わせることもできます。'": "title: '2. Load the song', text: 'Load an mp3 or similar file: JIZURA finds the beats and times the cuts to them. It also works without a song. “Tap to sync” lets you mark where each line starts.'",
    "title: '3. おまかせで作る', text: 'スタイル・雰囲気・動き・配色・構成をまるごと決めます。押すたびに別の案になり、「◀ 前の案」で戻れます。'": "title: '3. Create a variation', text: 'Style, mood, motion, palette and arrangement are chosen for you. Each press makes a new variation; “◀ Previous” goes back.'",
    "title: '4. 再生して確認する', text: '再生して見てみましょう。下のタイムラインでは、行の区切りをドラッグして動かせます（＋−で拡大）。'": "title: '4. Play it', text: 'Play it back. On the timeline below you can drag the line markers (+ and − zoom).'",
    "title: '5. 気になる行だけ直す', text: '行ごとに、歌詞を直す（✎）、カット数を決める、この行からタップし直す（◎）、この行だけ作り直す（サイコロ）ができます。'": "title: '5. Fix single lines', text: 'For each line you can edit the lyrics (✎), set the number of cuts, redo tap sync from that line (◎) or reroll just that line (dice).'",
    "title: '6. 書き出す', text: '画面比（縦長 9:16 など）と解像度を選んで MP4 を書き出します。「書き出す範囲」で選んだ行だけを書き出すこともできます。'": "title: '6. Export', text: 'Choose the aspect ratio (such as vertical 9:16) and resolution, then export MP4. “Export range” exports only the lines you pick.'",
    "'はじめる' : '次へ'": "'Start' : 'Next'",
    "'消音' : '音量'": "'Muted' : 'Vol'", "'音量 ' + Math.round": "'Volume ' + Math.round",
    '歌詞の言語：自動判定 → ': 'Lyrics language: auto-detect → ', '歌詞の言語：': 'Lyrics language: ',
    '${S.plan.cuts.length}カット': '${S.plan.cuts.length} cuts',
    '${i + 1}行目の開始秒': 'Line ${i + 1} start time (s)',
    'スタイル': 'Style', '雰囲気': 'Mood', '配色': 'Palette',
    '構成': 'Arrangement', '演出': 'Effects', '種': ' types',
    'のフォント': ' font',
    'で書き出します（': 'at (', '）。': '). ',
    '最初の公開版のあとに追加': 'Added after the original release', '和風の演出': 'Japanese motifs',
    'フォントを読み込み中…': 'Loading fonts…', '一時停止': 'Pause', '再生': 'Play',
    'この位置にカットはありません': 'No cut at this position',
    'スタイルの既定': 'Style default', '見出し書体': 'Display font',
    '見出し': 'Display', '明朝枠': 'Serif frame', '小さな文字': 'Small text',
    '背景の切替': 'Background changes', '動きの強さ': 'Motion strength',
    'カットの細かさ': 'Cut density', '装飾の量': 'Decoration amount',
    '文字の加工': 'Text treatments', '画面効果': 'Screen effects',
    'カット間のつなぎ': 'Transitions', 'レイアウト': 'Layout', '登場': 'Entrance',
    '保持': 'Hold', '退場': 'Exit', '装飾': 'Decoration', '加工': 'Treatment',
    'カメラ': 'Camera', 'つなぎ': 'Transition', '色ズレ': 'Color offset',
    'ズレ色A': 'Offset A', 'ズレ色B': 'Offset B', 'アクセント': 'Accent',
    '文字': 'Text', '補助': 'Secondary', '背景': 'Background',
    'グリッチ': 'Glitch', '質感': 'Texture',
    'この行の構成をロック': 'Lock this line', 'この行を再抽選': 'Reroll this line',
    'レイアウト指定': 'Choose layout', '開始（秒）': 'Start (s)',
    '・手動': ' · manual', '・自動': ' · automatic', '行目の開始秒': ' start time (s)',
    '行 / ': ' lines / ', 'カット': 'cuts', '行': 'line ',
    '自動': 'Auto', 'なし': 'None', 'カスタム': 'Custom',
    'ランダム': 'Random', '案目': 'variation', 'おまかせ：': 'Randomized: ',
    '配色：アクセント・ズレ色A/Bを変更': 'Palette: changed accent and offset colors',
    '構成：レイアウトと動きを再抽選': 'Arrangement: rerolled layout and motion',
    ' 種': ' types', '・': ' · ',
    'すべてON': 'All on', 'すべてOFF': 'All off', '反転': 'Invert',
    '（追加分がオフのため、おまかせでは選ばれません）': ' (new effects disabled for automatic picks)',
    '（和風の演出がオフのため、おまかせでは選ばれません）': ' (Japanese motifs disabled for automatic picks)',
    '（追加分がオフのため、自動では選ばれません）': ' (new effects disabled for automatic picks)',
    '（和風の演出がオフのため、自動では選ばれません）': ' (Japanese motifs disabled for automatic picks)',
    'グリーンバック': 'Green screen', 'ブラックバック': 'Black background',
    '白い文字と演出だけ': 'white text and effects only',
    '通常（スタイルの配色）': 'Style colors',
    'このブラウザは MP4 書き出しに対応していません（Chrome / Edge 推奨）': 'MP4 export is unavailable here (Chrome or Edge recommended)',
    'このブラウザでは ': 'This browser exports with ',
    '書き出し中はタブを開いたままにしてください。': 'Keep this tab open during export.',
    'このブラウザは動画エンコード（WebCodecs）に対応していません。Chrome / Edge の最新版で開くか、連番PNGを使ってください。': 'Video encoding (WebCodecs) is unavailable here. Try the latest Chrome or Edge, or export a PNG sequence.',
    '準備中…': 'Preparing…', '完成 ': 'Done: ', '秒': 's',
    '（保存はキャンセルされました）': ' (save canceled)', 'エラー: ': 'Error: ',
    '追加分の演出：使わない（最初の公開版の演出だけ）': 'New effects: off (original set only)',
    '追加分の演出：使う': 'New effects: on',
    '和風の演出：使わない（おまかせ・シャッフルで選ばれません）': 'Japanese motifs: off for random picks',
    '和風の演出：使う': 'Japanese motifs: on',
    'フォントを読み込めませんでした': 'Could not load the font',
    'プロジェクトを読み込めませんでした': 'Could not open the project',
    '解析中…': 'Analyzing audio…', '読み込めませんでした: ': 'Could not load: ',
    '約': 'about ', '（PC）': ' (installed)',
    '字面': 'JIZURA', '追加': 'New', '和': 'JP',
    'ループ': 'Loop',
    '行ループ': 'Line loop', 'カットループ': 'Cut loop',
    '全体を繰り返し': 'Loop the whole piece', 'この行を繰り返し': 'Loop this line',
    'このカットを繰り返し': 'Loop this cut', '繰り返しなし': 'No loop',
    # ロック（スライダー／手法の組／部品セット）
    "'おまかせでON／OFFを変えないようにロック'": "'Lock so Randomize keeps this group’s ON/OFF selection'",
    "'おまかせ／シャッフルで変えないようにロック'": "'Lock so Randomize / Shuffle leave this alone'",
    "'ロック中。クリックで解除'": "'Locked — click to unlock'",
    "'ロック：'": "'Locked: '",
    "'ロック解除：'": "'Unlocked: '",







    'この位置のカットは抽選できません': 'No cut at this position to re-roll',
    '`${i + 1}行目 カット${k + 1}のレイアウト`': '`Layout of cut ${k + 1} on line ${i + 1}`',
    'このカットだけ構成を再抽選': 'Re-roll the composition of only this cut',
    'このカットだけ手法をランダムに': 'Randomize the technique of only this cut',
    'このカットをシャッフル': 'Shuffle this cut',
    'このカットをおまかせ': 'Randomize this cut',
    'おまかせ': 'Randomize',
    'シャッフル': 'Shuffle',
}

EXPORT = {
    "'[間奏]'": "'[interlude]'",
    "'ZIP が大きくなりすぎます（65,535 ファイル・4GB まで）。書き出す範囲を狭めるか、解像度を下げてください'": "'The ZIP would be too large (65,535 files / 4 GB at most). Choose a shorter export range or a lower resolution'",
    "'エンコーダーが出力を返しません'": "'The encoder returned no output'",
    "'（ソフトウェア）'": "' (software)'",
    "'ファイルを仕上げ中'": "'Finishing the file'",
    '`動画のフレームが足りません（${outFrames}/${total}）`': '`Frames are missing (${outFrames}/${total})`',
    "'音声のエンコードに失敗しました: '": "'Audio encoding failed: '",
    "'エンコーダーが応答しません'": "'The encoder stopped responding'",
    "'「大きな動画用（ファイルに直接保存）」か、'": "'use “For large videos (save straight to a file)”, or '",
    '`（${vc.label}・ソフトウェアで再試行 ${k}）`': '` (${vc.label}, retry in software ${k})`',
    "'解像度・fps・画質を下げて試してください。詳細：'": "'try a lower resolution, fps or quality. Details: '",
    "'MP4 を書き出せませんでした。'": "'Could not export the MP4: '",
    "'エンコーダーが停止しました'": "'The encoder stopped'",
    "'音声のエンコードが途中で止まりました（' + aChunks + '）。もう一度書き出してください'": "'Audio encoding stopped partway (' + aChunks + '). Please export again'",
    'このブラウザは動画エンコード（WebCodecs）に対応していません。Chrome か Edge の最新版で開いてください。': 'Video encoding (WebCodecs) is unavailable. Open in the latest Chrome or Edge.',
    'キャンセルしました': 'Canceled', 'フレーム ': 'Frame ',
    '音声をエンコード中': 'Encoding audio', '完了': 'Done',
}

AE_UI = {
    "'文字PV系の部品を使う'": "'Use typographic parts'", "'キネティックの部品を使う'": "'Use kinetic parts'", "'ホラーの演出も使う'": "'Include horror effects'",
    "'線・数字・字組みだけで見せる、文字PVらしい部品（約50）'": "'About 50 parts that work with lines, numbers and type alone'",
    "'語ごとに動く・跳ねる・積み上がる、動き重視の部品（約50）'": "'About 50 motion-first parts: words move, bounce and stack one by one'",
    "'不気味な雰囲気の部品（約50）と配色セット3。オンにすると、おまかせの雰囲気に「ホラー」が加わります（ホラーの部品は雰囲気が「ホラー」のときだけ使います）'": "'About 50 eerie parts and 3 styles. When on, Randomize adds a Horror mood (horror parts are used only in that mood)'",
    "'  〔ホ〕'": "'  [H]'",
    "'\u3000縦長のとき'": "'  On tall frames'",
    "'上下に分ける'": "'Top / bottom'",
    "'左右に分ける'": "'Left / right'",
    "'軽量（AE での再生を軽く）'": "'Lightweight (faster playback in AE)'",
    "'色ズレの複製・紙の質感・グロー・粒子・一部の画面効果を省いて、After Effects での再生を軽くします（長い曲におすすめ）'": "'Leaves out the colour-shift copies, paper texture, bloom, grain and some screen effects so the composition plays back faster in After Effects (recommended for long songs)'",
    "'中央を空ける（キャラクター用：横長は左右・縦長は上下に配置）'": "'Keep the centre free (for a character: left / right on wide, top / bottom on tall frames)'",
    "'中央にキャラクターなどを重ねる前提で、文字と演出をカットごとの帯（横長の画面は左右、縦長は上下。行ごとに交互）に置きます。背景と画面効果は画面全体のままです'": "'For a character or other footage in the middle: each cut is laid out in a side band (left / right on wide frames, top / bottom on tall ones, alternating line by line). Backgrounds and screen effects still cover the whole frame.'",
    "'中止'": "'Stop'",
    "'作成を止めます（そこまでのカットでコンポを仕上げます）'": "'Stop building (the composition is finished with the cuts built so far)'",
    "'JIZURA：いま作成中です。終わるまで待つか「中止」を押してください'": "'JIZURA: a build is running. Wait for it to finish or press Stop.'",
    "' カット' : '効果を追加中'": "' cuts' : 'adding effects'",
    "'中止しています…（作成済みのカットで仕上げます）'": "'Stopping… (finishing with the cuts built so far)'",
    "'中止（' + job.done + ' / ' + job.total + ' カット）'": "'Stopped (' + job.done + ' / ' + job.total + ' cuts)'",
    '歌詞の言語': 'Lyrics language', "['自動判定', '日本語',": "['Auto-detect', '日本語',",
    '中国語（繁体字・簡体字）や韓国語の歌詞は、その文字を持つ書体で組みます（各スタイルの書体の雰囲気に近いものに置き換え）。自動判定はかな・ハングル・繁体字／簡体字に特有の字から判断します': 'Chinese (Traditional / Simplified) and Korean lyrics are set in fonts that have those characters, close in feel to each style. Auto-detect looks at kana, Hangul and the characters that differ between Traditional and Simplified Chinese.',
    "var JZ_SAMPLE = '夜明けの色を/覚えてる\\nほどけた声が遠くで鳴った\\nねえ、まだ間に合うかな\\n*透明*なままじゃ終われない!';": "var JZ_SAMPLE = 'I remember/the color of dawn\\nA voice faded into the distance\\nCan we still make it in time?\\n*Transparent* is not how this ends!';",
    'JIZURA 字面  lyric motion': 'JIZURA  lyric motion',
    '（': ' (', '）': ')', '部品': 'techniques',
    '歌詞（1行=1フレーズ　/ 区切り　*強調*　行末! インパクト）': 'One phrase per line. / = cut, *word* = emphasis, final ! = impact',
    'おまかせで生成（押すたびに別の演出）': 'Create a variation',
    'スタイル・雰囲気・演出の強さ・配色・シードをまるごとランダムに決めて、新しいコンポを作ります': 'Randomize style, mood, effects, colors and seed, then create a composition.',
    'オフのときは最初の公開版の演出（356部品・スタイル12種）だけを使います。オンにすると、あとから追加した演出・スタイル・書体も候補になります': 'Include techniques, styles and fonts added after the first release in random picks.',
    '提灯・はがき・障子・扇・家紋・青海波・桜の花びらなどの和風グラフィックと、和風のスタイル。オフにすると自動では選ばれません（追加分の判定のあとに適用）': 'Include Japanese motifs such as lanterns, shoji, fans and cherry blossoms in automatic picks.',
    'アクティブなコンポと同じ': 'Same as active comp',
    '通常（スタイルの背景）': 'Style background', 'グリーンバック（合成用）': 'Green screen (compositing)',
    'ブラックバック（合成用）': 'Black background (compositing)',
    'グリーンバック／ブラックバック：白い文字と演出だけを単色の背景の上に作ります（背景の模様・紙・粒子・周辺減光なし）。グリーンはキーイング、ブラックはスクリーン合成で抜けます': 'Solid green or black background behind white text and effects. Key out green or use Screen blending for black.',
    '自動（文字数・BPM から） / LRCの時刻': 'Auto (text length and BPM) / LRC timestamps',
    '選択レイヤーのマーカーを行頭に使う': 'Use selected layer markers for line starts',
    'コンポマーカーを行頭に使う': 'Use composition markers for line starts',
    '選択中の音声レイヤーを新しいコンポに入れる': 'Include selected audio layer in new composition',
    '標準（すべての手法を使う）': 'Standard (all techniques)',
    '雰囲気ごとに使うレイアウト・登場・退場の手法が絞られます（シードで再現）': 'Mood influences the selection of layouts, entrances and exits (reproducible by seed).',
    '背景に合うアクセント色とズレ色A/Bをランダムに選びます（明るさは背景に合わせて自動調整）': 'Randomize accent and offset colors with automatic brightness adjustment.',
    '配色を変更しました — 「コンポを生成する」で反映されます': 'Palette changed. Create a composition to apply it.',
    'ブラウザ版 JIZURA の「AE用に書き出し」で作った .json を読み込み、': 'Import a JSON file made with Export for AE in the browser app.',
    '同じタイミング・レイアウト・演出で編集可能なコンポを組みます。': 'Create an editable composition with the same timing, layouts and effects.',
    '思ったとおりにできないときは、下のボタンで診断レポート（JIZURA_report.txt）を保存して送ってください。': 'If the result looks wrong, save a diagnostic report (JIZURA_report.txt).',
    '診断レポートを保存（最後に作ったコンポ）': 'Save diagnostics for last composition',
    'PostScript名で指定（見つからない指定はここに落ちます）': 'Specify PostScript font names (fallbacks when a font is unavailable).',
    '常にこの4書体を使う（自動選択しない）': 'Always use these four fonts (disable automatic selection)',
    '選択中のテキストレイヤーの書体を「見出し」に': 'Use selected text layer font for display text',
    'Noto Sans JP / Noto Serif JP / Dela Gothic One などが入っていれば自動で使います（AE 2024以降）。': 'Installed Google Fonts are used automatically in After Effects 2024 or later.',
    'この PC に無い書体: ': 'Fonts missing on this computer: ',
    'JIZURA：次の書体がこの PC に無いため、近い書体で作りました。': 'JIZURA: These fonts are unavailable, so similar fonts were used.',
    'どれも Google Fonts（fonts.google.com）から無料で入れられます。入れて After Effects を再起動し、作り直すと、ブラウザ版と同じ書体になります。': 'Install them from Google Fonts, restart After Effects and rebuild for the closest browser match.',
    'JIZURA：この After Effects では書体が入っているかを確認できないため（AE 2024 より前）、「フォント」タブで指定した書体で作りました。': 'JIZURA: This version of After Effects cannot check installed fonts, so the font tab fallbacks were used.',
    'ブラウザ版と同じ書体にするには、使われている書体（Google Fonts）を入れて「フォント」タブで指定するか、AE 2024 以降で作ってください。': 'For matching type, install the Google Fonts used in the browser and select them in the font tab, or use AE 2024 or later.',
    'JIZURA：生成しましたが、一部に注意があります：': 'JIZURA: Composition created with some warnings:',
    'マーカーを使うには、コンポを開いてください': 'Open a composition to use markers',
    'マーカーのあるレイヤーを選択してください': 'Select a layer with markers',
    'マーカーが見つかりません': 'No markers found', 'マーカーを読めませんでした: ': 'Could not read markers: ',
    '構成の計算でエラー: ': 'Could not plan composition: ',
    '配色の値が読めないため、スタイルの色のままにしました（#RRGGBB 形式で入力）': 'Invalid color. Style colors were kept (enter #RRGGBB).',
    'JSONを読めませんでした: ': 'Could not read JSON: ',
    'JIZURA の AE用JSON ではないようです': 'This is not a JIZURA AE project JSON',
    'このパネルに無い表現 ': 'Techniques unavailable in this panel: ',
    'JIZURA：この JSON には、このパネルが作れない表現が ': 'JIZURA: This JSON contains ',
    ' 箇所あり、近い表現に置き換えました。': ' unsupported techniques; similar ones were substituted.',
    ' 箇所を、近い表現で作りました': ' instances were replaced by similar techniques',
    'ブラウザ版より古いパネルを使っている可能性があります。最新の JIZURA_AE.jsx（v': 'This panel may be older than the browser edition. Install the latest JIZURA_AE_en.jsx (v',
    '・860 部品）に差し替えて、After Effects を再起動してください。': ', 860 techniques) and restart After Effects.',
    '先にコンポを作ってください（このパネルで最後に作ったコンポを調べます）': 'Create a composition first; diagnostics inspect the last one created here.',
    '最後に作ったコンポが見つかりません（削除された可能性があります）': 'The last composition could not be found (it may have been deleted).',
    '診断中…（数十秒かかることがあります）': 'Diagnosing… (this can take a few seconds)',
    'レポートを保存しました：': 'Report saved: ',
    'レポートを保存できませんでした（環境設定 → スクリプトとエクスプレッション →「スクリプトによるファイルへの書き込みとネットワークへのアクセスを許可」をオンにしてください）。': 'Could not save report. Allow scripts to write files and access the network in After Effects preferences.',
    'テキストレイヤーを選択してください': 'Select a text layer', 'テキストレイヤーではありません': 'This is not a text layer',
    '追加分の演出も使う': 'Include new effects', '和風の演出も使う': 'Include Japanese motifs',
    '選択中の音声レイヤーも入れる': 'Include selected audio layer',
    'JSONを選んで生成…': 'Open JSON and build…',
    'スタイルの色を上書き': 'Override style colors', 'ランダム配色': 'Random palette',
    'コンポを生成する': 'Create composition', 'JSONから': 'From JSON', '歌詞から': 'From lyrics',
    'おまかせ：': 'Variation: ', 'ランダム配色': 'Random palette',
    '生成中…': 'Building…', '生成中にエラー: ': 'Build error: ',
    '診断：エクスプレッションのエラー ': 'Diagnostics: expression errors ',
    'JIZURA 診断：エクスプレッション ': 'JIZURA diagnostics: expressions ',
    ' 個のうち、エラー ': ', errors ', ' 個': '',
    '（時間の上限で途中まで）': ' (partial, time limit)', '（途中まで）': ' (partial)',
    '置換あり': 'Substitutions', '注意 ': 'Warnings: ', '件': '',
    '書体の代用 ': 'Font substitutions: ', '箇所': ' instances',
    '歌詞が空です': 'Lyrics are empty', '準備OK': 'Ready',
    '曲名': 'Song title', 'アーティスト': 'Artist', 'スタイル': 'Style',
    'サイズ': 'Size', '背景': 'Background', 'タイミング': 'Timing',
    '行の長さ': 'Line duration', '演出': 'Effects', '雰囲気': 'Mood',
    '動きの強さ': 'Motion strength', 'グリッチ': 'Glitch', '色ズレ': 'Color offset',
    '装飾の量': 'Decoration amount', 'カットの細かさ': 'Cut density',
    '質感': 'Texture', '背景の切替': 'Background changes',
    '2コマ打ち': 'On twos', 'フラッシュ': 'Flash',
    'スタイル次第': 'Auto by style', '非表示': 'Hide', '表示': 'Show',
    'シード': 'Seed', 'シャッフル': 'Shuffle',
    'アクセント・ズレ色': 'Accent and offset colors', 'アクセント': 'Accent',
    'ズレ色A': 'Offset A', 'ズレ色B': 'Offset B',
    'フォント': 'Fonts', '見出し': 'Display', '明朝': 'Serif',
    '小さな文字': 'Small text', '等幅': 'Monospace', '・': ' · ',
    '追加': 'New', '和': 'JP',
}

CEP = {
    '<label class="row ae-light-row" title="色ズレの複製・紙の質感・グロー・粒子・一部の画面効果を省いて、After Effects での再生を軽くします（長い曲におすすめ）"><input type="checkbox" class="ae-light"><span>軽量（AE での再生を軽く）</span></label>': '<label class="row ae-light-row" title="Leaves out the colour-shift copies, paper texture, bloom, grain and some screen effects so the composition plays back faster in After Effects (recommended for long songs)"><input type="checkbox" class="ae-light"><span>Lightweight (faster playback in AE)</span></label>',
    '選んだ範囲にカットがありません': 'No cuts in the selected range',
    "`${R.from + 1}${R.to > R.from ? '–' + (R.to + 1) : ''}行目・`": "`lines ${R.from + 1}${R.to > R.from ? '–' + (R.to + 1) : ''} · `",
    "'効果を追加中'": "'adding effects'",
    '`・残り約 ${Math.max(1, Math.round(left))} 秒`': '` · about ${Math.max(1, Math.round(left))} s left`',
    '`中止しました：「${r.name}」は ${r.cuts} / ${r.total} カットまでです`': '`Stopped: “${r.name}” has ${r.cuts} of ${r.total} cuts`',
    "'作成を中止しました'": "'Build stopped'",
    "'中止しています…（作成済みのカットで仕上げます）'": "'Stopping… (finishing with the cuts built so far)'",
    "'中止'": "'Stop'",
    "'作成を止めます（そこまでのカットでコンポを仕上げます）'": "'Stop building (the composition is finished with the cuts built so far)'",
    '「${r.name}」を作成しました': 'Created “${r.name}”',
    'AE の「${r.name}」で拍を合わせました': 'Synced beats to “${r.name}” in AE',
    '曲（<span class="ae-audio-name"></span>）をコンポに入れる': 'Include audio (<span class="ae-audio-name"></span>) in composition',
    ' に接続しました': ' connected',
    'After Effects に接続中…（初回は数秒かかります）': 'Connecting to After Effects…',
    'After Effects に接続しました': 'connected to After Effects',
    'After Effects に接続できませんでした: ': 'Could not connect to After Effects: ',
    'After Effects に接続できませんでした': 'Could not connect to After Effects',
    'この PC に無い書体（': 'Fonts missing on this computer (',
    '）は近い書体で作りました。Google Fonts から入れて AE を再起動すると、同じ書体になります': ') were replaced with similar fonts. Install them from Google Fonts and restart AE for a closer match.',
    'この AE（2024 より前）では書体の有無を確認できないため、スクリプト版パネルの「フォント」タブの書体（未設定なら游ゴシック・游明朝）で作りました': 'AE before 2024 cannot detect installed fonts; ScriptUI font settings or system fallbacks were used.',
    'レポートを保存できませんでした（AE の環境設定「スクリプトによるファイルへの書き込み…を許可」をオンに）': 'Could not save report. Enable script file writing in AE preferences.',
    'このパネルでは曲ファイルを直接読めません。「曲を読み込む」から選んでください': 'This panel cannot read audio directly. Use Import audio instead.',
    'この曲ファイルは読み込めませんでした（wav / mp3 / m4a などを使ってください）': 'Could not read this audio file. Try WAV, MP3 or M4A.',
    '最後に作ったコンポを調べて JIZURA_report.txt を保存します（うまく作れないときに送ってください）': 'Check the last composition and save a JIZURA_report.txt diagnostic file.',
    'AE で選択している曲のレイヤーを読み込み、拍に合わせます（コンポを作るときにその曲も入ります）': 'Import the selected AE audio layer, analyze beats and include it in the composition.',
    '選択レイヤー（無ければコンポ）のマーカーを、各行の開始時刻にします': 'Use selected layer markers (or composition markers) for line start times.',
    '今の構成で After Effects にコンポを作ります': 'Build an After Effects composition from this arrangement.',
    '診断中…（数十秒かかることがあります）': 'Diagnosing… (this may take a few seconds)',
    'コンポを作成中…': 'Building composition…',
    'AEで選択中の曲': 'Selected AE audio',
    'AEのマーカーを行頭に': 'Use AE markers for lines',
    'AEでコンポを生成': 'Build in AE',
    'After Effects にコンポを作る': 'Build composition in After Effects',
    'After Effects にコンポを作成しました': 'Composition created in After Effects',
    '診断レポートを保存': 'Save diagnostic report',
    'コンポに入れる': 'include in composition',
    '作成できませんでした: ': 'Could not create composition: ',
    '作成できませんでした': 'Could not create composition',
    '近い表現で置換 ': 'Substitutions: ', '注意 ': 'Warnings: ',
    '診断：エクスプレッション ': 'Diagnostics: expressions ',
    ' 個のうちエラー ': ', errors ', ' 個': '', '（途中まで）': ' (partial)',
    '曲ファイルを読めませんでした: ': 'Could not read audio: ',
    'この曲ファイルは読み込めませんでした': 'Could not read this audio file',
    'のマーカー ': ' markers: ', ' 個を行の開始時刻にしました': ' line start times set',
    'レイヤー': 'Layer', 'コンポ': 'Composition',
    '（残り ': ' (remaining ', ' 行は自動）': ' lines automatic)',
    '動画・画像': 'Video and images',
    '保存しました: ': 'Saved: ', '保存': 'Save',
    ' カット': ' cuts', ' 秒': ' s', '曲入り': 'with audio',
    ' 箇所': ' instances', ' 件': ' items', 'レポート: ': 'Report: ',
    '「': '“', '」': '”', '（': ' (', '）': ')', '・': ' · ',
}

CEP_HOST = {
    "'生成中のコンポがありません'": "'No composition is being built'",
    'JIZURA の構成データではありません': 'This is not JIZURA project data',
    'コンポを開いて、曲のレイヤーを選択してください': 'Open a composition and select an audio layer',
    '曲（音声ファイル）のレイヤーを選択してください': 'Select an audio file layer',
    'コンポを開いてください': 'Open a composition',
    'マーカーが見つかりません（曲のレイヤーかコンポにマーカーを打ってください）': 'No markers found. Add markers to the audio layer or composition.',
    '構成データの一時ファイルが見つかりません': 'Temporary project data file not found',
    '先にこのパネルでコンポを作ってください': 'Create a composition in this panel first',
}


def localize_cep(source, host=False):
    return replace_copy(source, CEP_HOST if host else CEP)


def localize_ae(source):
    return (replace_copy(source, AE_UI)
            .replace('lyr.preferredSize = [340, 150]', 'lyr.preferredSize = [440, 150]')
            .replace('preferredSize.width = 86', 'preferredSize.width = 120')
            .replace('preferredSize.width = 70', 'preferredSize.width = 95'))


def replace_copy(source, glossary):
    # Longest first protects complete phrases from shorter label replacements.
    for japanese, english in sorted(glossary.items(), key=lambda pair: -len(pair[0])):
        source = source.replace(japanese, english)
    return source


def localize_body(source):
    return replace_copy(source, BODY).replace('You own the<strong>', 'You own the <strong>')


def localize_js(source, filename):
    if filename.endswith('12_ui.js'):
        return replace_copy(source, UI)
    if filename.endswith('11_export.js'):
        return replace_copy(source, EXPORT)
    return source
